<?php
return[
    [
        'title'=>'Dashboard',
        'route'=>'dashboard',
        'icon'=>'ti-home',
    ],
    [
        'title'=>'Parent',
        'route'=>'parent.index',
        'icon'=>'ti-menu-alt',
    ],
    [
        'title'=>'School Grade',
        'route'=>'schoolGrade.index',
        'icon'=>'ti-menu-alt',
        'badge'=>'New',
    ],
    [
        'title'=>'Classroom',
        'route'=>'classroom.index',
        'icon'=>'ti-menu-alt',
    ],
    [
        'title'=>'Section',
        'route'=>'section.index',
        'icon'=>'ti-menu-alt',
    ],
    [
        'title'=>'Specialization',
        'route'=>'specialization.index',
        'icon'=>'ti-menu-alt',
    ],
    [
        'title'=>'Teacher',
        'route'=>'teacher.index',
        'icon'=>'ti-menu-alt',
    ],
    [
        'title'=>'Studant',
        'route'=>'studant.index',
        'icon'=>'ti-menu-alt',
    ],
    [
        'title'=>'Promotion',
        'route'=>'promotion.index',
        'icon'=>'ti-menu-alt',
    ],
    [
        'title'=>'Accounts',
        'route'=>'account.index',
        'icon'=>'ti-menu-alt',
    ],
    [
        'title'=>'Subjects',
        'route'=>'subject.index',
        'icon'=>'ti-menu-alt',
    ],
    [
        'title'=>'Exams',
        'route'=>'exam.index',
        'icon'=>'ti-menu-alt',
    ],
    [
        'title'=>'Exam Question',
        'route'=>'examQuestion.index',
        'icon'=>'ti-menu-alt',
    ],

    [
        'title'=>'Sitting',
        'route'=>'setting.edit',
        'icon'=>'ti-menu-alt',
    ],
    [
        'title'=>'Online Class',
        'route'=>'onlineClass.index',
        'icon'=>'ti-menu-alt',
    ],
    ];
